name: spectre_agent
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Telegram Bot API
  televerse: ^1.7.2 # A modern, null-safe library
  # Background Service
  flutter_background_service: ^5.0.1
  # Core Functionality
  camera: ^0.10.5+9
  geolocator: ^11.0.0
  record: ^5.0.5
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  device_info_plus: ^10.1.0
  wifi_iot: ^0.3.18+1
  flutter_contacts: ^1.1.7+1
  # Self-Update
  dio: ^5.4.3+1
  open_file: ^3.3.2
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
