name: Build Pong APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create Cordova project
        run: cordova create pong-app com.example.pong PongApp

      - name: Copy game files
        run: cp index.html style.css game.js pong-app/www/

      - name: Add Android platform
        run: cd pong-app && cordova platform add android --save

      - name: Build APK
        run: cd pong-app && cordova build android

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: pong-apk
          path: pong-app/platforms/android/app/build/outputs/apk/debug/app-debug.apk
